### ISSUE TITLE
[Bug] execjs._exceptions.ProgramError: SyntaxError: 语法错误

### ISSUE THREAD

**Issue by Kuron88** [Physton/sd-webui-prompt-all-in-one#225]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

Exception in thread Thread-100 (process_keywords):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\sd.webui\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\slugify.py", line 96, in process_keywords
    result = ctx.call('slugifyMulti', keywords)
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\sd.webui\system\python\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 语法错误

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

1.6

**Comment by Physton** [comment]
如有有造成插件无法使用，先退回老版本，这个是环境问题，不好马上解决。

**Comment by cenfun** [comment]
```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\slugify.py", line 96, in process_keywords
    result = ctx.call('slugifyMulti', keywords)
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_external_runtime.py", line 87, in _exec_
    output = self._exec_with_pipe(source)
  File "stable-diffusion-webui\venv\lib\site-packages\execjs\_external_runtime.py", line 103, in _exec_with_pipe
    stdoutdata, stderrdata = p.communicate(input=input)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1520, in _communicate
    self._stdin_write(input)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1086, in _stdin_write
    self.stdin.write(input)
UnicodeEncodeError: 'gbk' codec can't encode character '\u4336' in position 166691: illegal multibyte sequence
```

**Comment by Physton** [comment]
@Kuron88 @cenfun 
Version: 61f103e9faa7fd117e3d148e07429499ca060736
先屏蔽了异常，这个功能暂时无法使用，不影响插件的正常使用。
Blocked the exception for now, this feature is temporarily unavailable but does not affect the normal use of the plugin.

**Comment by Physton** [comment]
@Kuron88 @cenfun 更新到目前最新版本再看看。

**Comment by cenfun** [comment]
确认已经修复
