### ISSUE TITLE
[Bug] API Error

### ISSUE THREAD

**Issue by angryptonX** [Physton/sd-webui-prompt-all-in-one#249]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

Since last update of every extensions i get this Error. When i start the UI its everything fine but after generate a image and change something in the prompts like double-tap to disable or Emphasize a tag, the error occurs.

### Screenshot or log

*** API error: POST: http://127.0.0.1:7860/physton_prompt/install_package {'error': 'JSONDecodeError', 'detail': '', 'body': '', 'errors': 'Expecting value: line 1 column 1 (char 0)'}
    Traceback (most recent call last):
      File "G:\Dokumente\AI\stable-diffusion-webui\modules\api\api.py", line 187, in exception_handling
        return await call_next(request)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "G:\Dokumente\AI\stable-diffusion-webui\modules\api\api.py", line 151, in log_and_time
        res: Response = await call_next(req)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
        await self.app(scope, receive, send)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
        await responder(scope, receive, send)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
        await self.app(scope, receive, self.send_with_gzip)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
        return await dependant.call(**values)
      File "G:\Dokumente\AI\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 87, in _install_package
        data = await request.json()
      File "G:\Dokumente\AI\stable-diffusion-webui\venv\lib\site-packages\starlette\requests.py", line 244, in json
        self._json = json.loads(body)
      File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

---

### OS

Windows

### Browser

Firefox

### Stable Diffusion WebUI version

1.6.0

### Extension version

a612da3c

### Python version

3.10.11

### Gradio version

3.41.2

**Comment by Physton** [comment]
Update to the latest version and try again.

**Comment by droide** [comment]
Error code: 405

**Comment by tiller** [comment]
For the record, I had the same issue, same log and 404 error in the UI. I fixed it with `rm extensions/sd-webui-prompt-all-in-one/storage/*.lock` (but lost history)
