### ISSUE TITLE
当历史记录包含中文字符时，重新启动webUI时，插件初始化时出现解析不了历史JSON的问题

### ISSUE THREAD

**Issue by HalfMAI** [Physton/sd-webui-prompt-all-in-one#28]
1.当历史记录包含中文字符时
2.重新启动webUI时
3.插件初始化时出现解析不了历史JSON的问题

Log 如下：

Error executing callback app_started_callback for F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py
Traceback (most recent call last):
  File "F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\modules\script_callbacks.py", line 108, in app_started_callback
    c.callback(demo, app)
  File "F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 18, in on_app_started
    hi = history()
  File "F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\history.py", line 23, in __init__
    self.histoies[type] = self.storage.get('history.' + type)
  File "F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\storage.py", line 75, in get
    return self.__get(key)
  File "F:\_DEV\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\storage.py", line 55, in __get
    data = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 3779: illegal multibyte sequence

**Comment by Physton** [comment]
不是中文的问题，我这一直有中文，我不知道为什么文件编码发生了问题，我已经加上了自动检测文件编码，你更新后再试一试。
