### ISSUE TITLE
[Bug] download the source code，copy into extensions，can not start

### ISSUE THREAD

**Issue by ibmxiang** [Physton/sd-webui-prompt-all-in-one#311]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

 Error executing callback app_started_callback for /home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/on_app_started.py
    Traceback (most recent call last):
      File "/home/xls/stable-diffusion-webui/modules/script_callbacks.py", line 139, in app_started_callback
        c.callback(demo, app)
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/on_app_started.py", line 61, in on_app_started
        hi = History()
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/physton_prompt/history.py", line 24, in __init__
        self.histories[type] = self.storage.get('history.' + type)
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/physton_prompt/storage.py", line 95, in get
        return self.__get(key)
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/physton_prompt/storage.py", line 53, in __get
        filename = self.__get_data_filename(key)
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/physton_prompt/storage.py", line 33, in __get_data_filename
        return self.__get_storage_path() + '/' + key + '.json'
      File "/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/scripts/physton_prompt/storage.py", line 17, in __get_storage_path
        os.makedirs(self.storage_path)
      File "/usr/local/python3/lib/python3.10/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/storage'

### OS

Other Linux

### Browser

Chrome

**Comment by Physton** [comment]
```bash
chmod -R 777 /home/xls/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one-main/storage
```
