### ISSUE TITLE
[Bug] 扩展程序已停止工作 

### ISSUE THREAD

**Issue by jthwxxzyt** [Physton/sd-webui-prompt-all-in-one#346]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

sd-webui-prompt-all-in-one
Connection to backend API service failed. Please manually refresh the webpage. If it still doesn't work, please restart the WebUI.
连接到后台接口服务失败，请手动再刷新一次网页。如果还是不行，请重启WebUI。

我查阅了以前的问题，这个好像是更新导致的错误，以前使用该插件并没有出现这个问题。

### 如何复现

正常使用stablediffusion

### 截图或日志

![(MX0V@)T N 42OQJ%M}DHU9](https://github.com/user-attachments/assets/931af87a-3523-4c93-abe6-ed2256433b54)

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

version: f1.0.2v1.10.1-previous-186-g653be0a3  

### Python 版本

python: 3.10.12

### Gradio 版本

gradio: 4.40.0

**Comment by wrathgoddess** [comment]
same problem for me as well.
 
*** Error loading script: on_app_started.py
    Traceback (most recent call last):
      File "J:\FORGED\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\FORGED\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 10, in <module>
        from scripts.physton_prompt.get_token_counter import get_token_counter
      File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py", line 2, in <module>
        from modules.sd_hijack import model_hijack
    ImportError: cannot import name 'model_hijack' from 'modules.sd_hijack' (J:\FORGED\webui\modules\sd_hijack.py)

**Comment by jthwxxzyt** [comment]
> 我也有同样的问题。
> 
> *** 加载脚本时出错：on_app_started.py 回溯（最近一次调用最后一次）： 文件“J:\FORGED\webui\modules\scripts.py”，第525行，在load_scripts中 script_module = script_loading.load_module（scriptfile） .path） 文件“J:\FORGED\webui\modules\script_loading.py”，第13行，在load_module中 module_spec.loader.exec_module（module） 文件“”，第883行，在exec_module文件中 “”，第241行，在 _call_with_frames_removed 中 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py”，第10行，来自 scripts.physton_prompt.get_token_counter导入 get_token_counter 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py”，第2行，来自 modules.sd_hijack 导入 model_hijack ImportError：无法从'modules. sd_hijack'导入名称'model_hijack'（J:\FORGED\webui\modules\sd_hijack.py）

This seems to be a problem caused by the sd update, I found that more than one plugin is not working [not shown].

**Comment by jthwxxzyt** [comment]
> 我也有同样的问题。
> 
> *** 加载脚本时出错：on_app_started.py 回溯（最近一次调用最后一次）： 文件“J:\FORGED\webui\modules\scripts.py”，第525行，在load_scripts中 script_module = script_loading.load_module（scriptfile） .path） 文件“J:\FORGED\webui\modules\script_loading.py”，第13行，在load_module中 module_spec.loader.exec_module（module） 文件“”，第883行，在exec_module文件中 “”，第241行，在 _call_with_frames_removed 中 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py”，第10行，来自 scripts.physton_prompt.get_token_counter导入 get_token_counter 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py”，第2行，来自 modules.sd_hijack 导入 model_hijack ImportError：无法从'modules. sd_hijack'导入名称'model_hijack'（J:\FORGED\webui\modules\sd_hijack.py）

这个好像是由于sdforge更新引起的问题，我发现不止一个插件不工作[未显示]。

**Comment by yelinli** [comment]
> > 我也有同样的问题。
> > *** 加载脚本时出错：on_app_started.py 回溯（最近一次调用最后一次）： 文件“J:\FORGED\webui\modules\scripts.py”，第525行，在load_scripts中 script_module = script_loading.load_module（scriptfile） .path） 文件“J:\FORGED\webui\modules\script_loading.py”，第13行，在load_module中 module_spec.loader.exec_module（module） 文件“”，第883行，在exec_module文件中 “”，第241行，在 _call_with_frames_removed 中 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py”，第10行，来自 scripts.physton_prompt.get_token_counter导入 get_token_counter 文件“J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py”，第2行，来自 modules.sd_hijack 导入 model_hijack ImportError：无法从'modules. sd_hijack'导入名称'model_hijack'（J:\FORGED\webui\modules\sd_hijack.py）
> 
> 这个好像是由于sdforge更新引起的问题，我发现不止一个插件不工作[未显示]。

我上午运行forge，这个插件很正常，刚刚更新了forge后这个插件就没办法加载了，希望作者能够修复这个问题

**Comment by wrathgoddess** [comment]
> same problem for me as well.
> 
> *** Error loading script: on_app_started.py Traceback (most recent call last): File "J:\FORGED\webui\modules\scripts.py", line 525, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "J:\FORGED\webui\modules\script_loading.py", line 13, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 10, in from scripts.physton_prompt.get_token_counter import get_token_counter File "J:\FORGED\webui\extensions\sd-webui-prompt-all-in-one\scripts\physton_prompt\get_token_counter.py", line 2, in from modules.sd_hijack import model_hijack ImportError: cannot import name 'model_hijack' from 'modules.sd_hijack' (J:\FORGED\webui\modules\sd_hijack.py)


update was made some fixes seems to be working but 

sd-webui-prompt-all-in-one background API service started successfully.
*** Error loading script: attention.py
    Traceback (most recent call last):
      File "J:\FORGED\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\FORGED\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\FORGED\webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 3, in <module>
        import ldm.modules.attention as atm
    ModuleNotFoundError: No module named 'ldm'

**Comment by NarakoYo** [comment]
+1

**Comment by wojoco** [comment]
楼主，你的问题解决没有？

**Comment by NarakoYo** [comment]
今天启动又可以正常使用，非常奇妙


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月16日(周五) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Physton/sd-webui-prompt-all-in-one] [Bug] 扩展程序已停止工作  (Issue #346)




 
楼主，你的问题解决没有？
 
&mdash;

**Comment by wuyougg** [comment]
I also encountered this problem, what are your sdforge and extended versions?

**Comment by xiansk** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/98#issuecomment-3380513935
