### ISSUE TITLE
求助！To create a public link, set `share=True` in `launch()`.

### ISSUE THREAD

**Issue by bubbl000** [Physton/sd-webui-prompt-all-in-one#41]
To create a public link, set `share=True` in `launch()`.
Error executing callback app_started_callback for E:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py
Traceback (most recent call last):
  File "E:\ai\stable-diffusion-webui\modules\script_callbacks.py", line 107, in app_started_callback
    c.callback(demo, app)
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 18, in on_app_started
    hi = history()
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\history.py", line 23, in __init__
    self.histoies[type] = self.storage.get('history.' + type)
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\storage.py", line 75, in get
    return self.__get(key)
  File "E:\ai\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\storage.py", line 55, in __get
    data = json.load(f)
  File "C:\Users\lin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\lin\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lin\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10761 column 26 (char 331785)

 这个扩展可以使用，但是cmd启动的时候一直会出现这个代码 我不知道是不是出错了

**Comment by Physton** [comment]
你需要更新此扩展
